const RESET_DISPLAY = 'RESET_DISPLAY'
const SET_EXPRESSION = 'SET_EXPRESSION'
const SET_NUMBER = 'SET_NUMBER'
const CALCULATE = 'CALCULATE'

export { RESET_DISPLAY, SET_EXPRESSION, SET_NUMBER, CALCULATE }
